// js/data.js
const products = [
    {
        id: 1,
        name: "Alphonso Mangoes",
        price: 92463,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400",
        ripeness: 85,
        ripenessLevel: "ready",
        origin: "india",
        organic: true,
        sugar: "high",
        mood: "indulgent",
        description: "Premium Alphonso mangoes from Ratnagiri. Known as the king of fruits for their rich, creamy sweetness.",
        farm: "Sunshine Orchards, Maharashtra",
        tasteProfile: { sweet: 90, tangy: 20, bitter: 5 }
    },
    {
        id: 2,
        name: "Organic Blueberries",
        price: 33263,
        image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400",
        ripeness: 95,
        ripenessLevel: "ready",
        origin: "usa",
        organic: true,
        sugar: "medium",
        mood: "healthy",
        description: "Sweet and antioxidant-rich blueberries picked at peak ripeness.",
        farm: "Berry Fields, Oregon",
        tasteProfile: { sweet: 70, tangy: 40, bitter: 10 }
    },
    {
        id: 3,
        name: "Dragon Fruit",
        price: 48063,
        image: "https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=400",
        ripeness: 70,
        ripenessLevel: "ripening",
        origin: "thailand",
        organic: false,
        sugar: "low",
        mood: "exotic",
        description: "Exotic dragon fruit with stunning pink skin and white flesh.",
        farm: "Tropical Paradise Farms, Thailand",
        tasteProfile: { sweet: 60, tangy: 15, bitter: 5 }
    },
    {
        id: 4,
        name: "Honeycrisp Apples",
        price: 25863,
        image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400",
        ripeness: 100,
        ripenessLevel: "ready",
        origin: "usa",
        organic: true,
        sugar: "medium",
        mood: "comfort",
        description: "Crisp, juicy apples with the perfect balance of sweet and tart.",
        farm: "Apple Valley Orchards, Washington",
        tasteProfile: { sweet: 75, tangy: 50, bitter: 0 }
    },
    {
        id: 5,
        name: "Organic Bananas",
        price: 18463,
        image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
        ripeness: 60,
        ripenessLevel: "green",
        origin: "mexico",
        organic: true,
        sugar: "high",
        mood: "energetic",
        description: "Naturally sweet bananas perfect for smoothies.",
        farm: "Green Valley Farms, Mexico",
        tasteProfile: { sweet: 85, tangy: 5, bitter: 0 }
    },
    {
        id: 6,
        name: "Sugar Baby Watermelon",
        price: 36963,
        image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
        ripeness: 90,
        ripenessLevel: "ready",
        origin: "local",
        organic: true,
        sugar: "high",
        mood: "refreshing",
        description: "Personal-sized watermelons bursting with sweet juice.",
        farm: "Local Family Farm, California",
        tasteProfile: { sweet: 95, tangy: 10, bitter: 0 }
    },
    {
        id: 7,
        name: "Italian Blood Oranges",
        price: 55463,
        image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400",
        ripeness: 88,
        ripenessLevel: "ready",
        origin: "italy",
        organic: true,
        sugar: "medium",
        mood: "energetic",
        description: "Striking blood oranges with deep red flesh and complex berry notes.",
        farm: "Sicilian Groves, Italy",
        tasteProfile: { sweet: 70, tangy: 60, bitter: 15 }
    },
    {
        id: 8,
        name: "Avocados",
        price: 29563,
        image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400",
        ripeness: 75,
        ripenessLevel: "ripening",
        origin: "mexico",
        organic: true,
        sugar: "low",
        mood: "healthy",
        description: "Creamy Hass avocados perfect for toast.",
        farm: "Avocado Estates, Michoacán",
        tasteProfile: { sweet: 20, tangy: 10, bitter: 30 }
    }
];